In [1]:
import math as mt
import numpy as np

In [6]:
class transf3D:
    def __init__(self):
        self.matriz = np.array([[1,0,0,0],
                                [0,1,0,0],
                                [0,0,1,0],
                                [0,0,0,1]])
        
    def reset(self):
        self.matriz = np.array([[1,0,0,0],
                                [0,1,0,0],
                                [0,0,1,0],
                                [0,0,0,1]])
    
    def translacao(self, x, y, z):
        target = np.array([[1,0,0,x],
                           [0,1,0,y],
                           [0,0,1,z],
                           [0,0,0,1]])
        self.matriz = target.dot(self.matriz)
        
    def escala(self, x, y, z):
        target = np.array([[x,0,0,0],
                           [0,y,0,0],
                           [0,0,z,0],
                           [0,0,0,1]])
        self.matriz = target.dot(self.matriz)
    
    def rotacaox(self, a):
        r = mt.radians(a)
        target = np.array([[1,0,0,0],
                           [0,mt.cos(r),mt.sin(r)*-1, 0],
                           [0,mt.sin(r),mt.cos(r), 0],
                           [0,0,0,1]])
        self.matriz = target.dot(self.matriz)
    
    def rotacaoy(self, a):
        r = mt.radians(a)
        target = np.array([[mt.cos(r),0,mt.sin(r),0],
                           [0,1,0,0],
                           [mt.sin(r)*-1,0,mt.cos(r),0],
                           [0,0,0,1]])
        self.matriz = target.dot(self.matriz)
        
    def rotacaoz(self, a):
        r = mt.radians(a)
        target = np.array([[mt.cos(r),mt.sin(r)*-1,0,0],
                           [mt.sin(r),mt.cos(r),0,0],
                           [0,0,1,0],
                           [0,0,0,1]])
        self.matriz = target.dot(self.matriz)
        
    def aplicar(self, p):
        point = self.matriz.dot(p)
        res = [point[0], point[1], point[2]]
        return res;
    
    def menu(self):
         while(True):
            print("\n\nA matriz atual é: \n" + str(self.matriz))
            print("1. Translacao")
            print("2. Escala")
            print("3. Rotação em X")
            print("4. Rotação em Y")
            print("5. Rotação em Z")
            print("6. Aplicar a um ponto")
            print("7. Resetar")
            print("0. Finalizar operações\n")
            
            opt = int(input("opção: "))
            if(not opt):
                break
            if(opt == 0):
                break
            elif(opt == 1):
                a = int(input("Digite o valor de x: "))
                b = int(input("Digite o valor de y: "))
                c = int(input("Digite o valor de z: "))
                self.translacao(a, b, c)
                
            elif(opt == 2):
                a = int(input("Digite o valor de x: "))
                b = int(input("Digite o valor de y: "))
                c = int(input("Digite o valor de z: "))
                self.escala(a, b, c)
                
            elif(opt == 3):
                a = float(input("Digite o valor do ângulo: "))
                self.rotacaox(a)
                
            elif(opt == 4):
                a = float(input("Digite o valor do ângulo: "))
                self.rotacaoy(a)
            
            elif(opt == 5):
                a = float(input("Digite o valor do ângulo: "))
                self.rotacaoz(a)
                
            elif(opt == 6):
                a = int(input("Digite o valor de x: "))
                b = int(input("Digite o valor de y: "))
                c = int(input("Digite o valor de z: "))
                
                p = np.array([a, b, c, 1])

                print("O ponto é: " + str(self.aplicar(p)))
                
            elif(opt == 7):
                self.reset()
                
            input("Pressione ENTER para prosseguir\n")
            print("\n\n\n\n")
    

In [7]:
tf = transf3D()
tf.menu()



A matriz atual é: 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
1. Translacao
2. Escala
3. Rotação em X
4. Rotação em Y
5. Rotação em Z
6. Aplicar a um ponto
7. Resetar
0. Finalizar operações

opção: 1
Digite o valor de x: 2
Digite o valor de y: 3
Digite o valor de z: 4
Pressione ENTER para prosseguir








A matriz atual é: 
[[1 0 0 2]
 [0 1 0 3]
 [0 0 1 4]
 [0 0 0 1]]
1. Translacao
2. Escala
3. Rotação em X
4. Rotação em Y
5. Rotação em Z
6. Aplicar a um ponto
7. Resetar
0. Finalizar operações

opção: 2
Digite o valor de x: 2
Digite o valor de y: 2
Digite o valor de z: 2
Pressione ENTER para prosseguir








A matriz atual é: 
[[2 0 0 4]
 [0 2 0 6]
 [0 0 2 8]
 [0 0 0 1]]
1. Translacao
2. Escala
3. Rotação em X
4. Rotação em Y
5. Rotação em Z
6. Aplicar a um ponto
7. Resetar
0. Finalizar operações

opção: 6
Digite o valor de x: 2
Digite o valor de y: 2
Digite o valor de z: 2
O ponto é: [8, 10, 12]
Pressione ENTER para prosseguir








A matriz atual é: 
[[2 0 0 4]
 [0 2 0 6]
 